"""remove pose from face embeddings

Revision ID: 17fd85a632fb
Revises: 591a9cb04108
Create Date: 2026-08-11 22:07:20.270655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fd85a632fb'
down_revision: Union[str, Sequence[str], None] = '591a9cb04108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_embeddings', 'pose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('pose', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
