"""add teacher to attendance sessions

Revision ID: 3b84db098e52
Revises: 915bceeaca1d
Create Date: 2026-08-13 15:31:36.275195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b84db098e52'
down_revision: Union[str, Sequence[str], None] = '915bceeaca1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'attendance_sessions', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_column('attendance_sessions', 'teacher_id')
    # ### end Alembic commands ###
